function bzb(a){this.b=a}
function ezb(a){this.b=a}
function hzb(a){this.b=a}
function _G(a){JG();return new $G(HG.Xd(),a,false)}
function Xyb(a,b){if(b==null){aj(a.d,EOc)}else{u4b(a.d,b);Vi(a.d,EOc)}}
function bkb(a){var b,c;b=FV(a.b.ne(zOc),147);if(b==null){c=vV(Ueb,VCc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.b.pe(zOc,c);return c}else{return b}}
function Yyb(b){var c,d,e;d=(qYb(),Vr(b.g.db,DLc));if(Xsc(d,oFc)){u4b(b.d,FOc)}else{try{e=dsc(d);c=OG(b.b,e);u4b(b.d,c);Xyb(b,null)}catch(a){a=cfb(a);if(HV(a,143)){Xyb(b,GOc)}else throw bfb(a)}}}
function Wyb(a){var b,c,d,e,f;b=new L7b(4,2);qYb();ds(b.p,OJc,5);a.f=new hac;ij(a.f,AOc);f=bkb(a.c);for(d=0,e=f.length;d<e;++d){c=f[d];cac(a.f,c)}Cj(a.f,new bzb(a),(uy(),uy(),ty));_6b(b,0,0,BOc);c7b(b,0,1,a.f);a.e=new Ucc;ij(a.e,AOc);Cj(a.e,new ezb(a),(hz(),hz(),gz));c7b(b,1,1,a.e);a.g=new Ucc;ij(a.g,AOc);Kcc(a.g,'31415926535.897932');Cj(a.g,new hzb(a),gz);_6b(b,2,0,COc);c7b(b,2,1,a.g);a.d=new w4b;ij(a.d,AOc);_6b(b,3,0,DOc);c7b(b,3,1,a.d);Zyb(a);return b}
function Zyb(b){var c;switch(b.f.db.selectedIndex){case 0:b.b=(JG(),!EG&&(EG=new $G(HG.Yd(),BD((_C(),$C)),false)),JG(),EG);Kcc(b.e,b.b.u);G_b(b.e,false);break;case 1:b.b=(JG(),!DG&&(DG=_G(BD((_C(),$C)))),JG(),DG);Kcc(b.e,b.b.u);G_b(b.e,false);break;case 2:b.b=(JG(),!GG&&(GG=new $G(HG.ie(),BD((_C(),$C)),false)),JG(),GG);Kcc(b.e,b.b.u);G_b(b.e,false);break;case 3:b.b=(JG(),!FG&&(FG=new $G(HG.he(),BD((_C(),$C)),false)),JG(),FG);Kcc(b.e,b.b.u);G_b(b.e,false);break;case 4:G_b(b.e,true);c=(qYb(),Vr(b.e.db,DLc));try{b.b=(JG(),new $G(c,BD((_C(),$C)),true))}catch(a){a=cfb(a);if(HV(a,139)){Xyb(b,HOc);return}else throw bfb(a)}}Yyb(b)}
var wOc='#,##0.00\xA0\xA4',xOc='#,##0\xA0%',yOc='#E0',zOc='cwNumberFormatPatterns';var DG,FG,GG;_fb(356,1,{});_.Xd=function mH(){return wOc};_.he=function yH(){return xOc};_.ie=function zH(){return yOc};_fb(357,1,{});_.Xd=function DH(){return wOc};_.he=function PH(){return xOc};_.ie=function QH(){return yOc};_fb(358,1,{});_.Xd=function UH(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.he=function eI(){return xOc};_.ie=function fI(){return yOc};_fb(359,1,{});_.Xd=function jI(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.he=function vI(){return xOc};_.ie=function wI(){return yOc};_fb(360,1,{});_.Xd=function AI(){return wOc};_.he=function MI(){return xOc};_.ie=function NI(){return yOc};_fb(361,1,{});_.Xd=function RI(){return wOc};_.he=function bJ(){return xOc};_.ie=function cJ(){return yOc};_fb(671,1,GDc,bzb);_.Gc=function czb(a){Zyb(this.b)};_fb(672,1,qDc,ezb);_.Jc=function fzb(a){Zyb(this.b)};_fb(673,1,qDc,hzb);_.Jc=function izb(a){Yyb(this.b)};_fb(674,1,IDc);_.qc=function mzb(){Fib(this.c,Wyb(this.b))};var J3=Trc(LKc,'CwNumberFormat$1',671),K3=Trc(LKc,'CwNumberFormat$2',672),L3=Trc(LKc,'CwNumberFormat$3',673);vEc(Vn)(25);