function i8(){}
function Cvc(a,b){OC(a.a,b)}
function EXb(a,b){this.b=a;this.a=b}
function HXb(a,b){this.b=a;this.a=b}
function H8(a){return oyb(s8,a)}
function h8(){h8=aWc;g8=new i8}
function wXb(a,b){hnc(b,Bvd+a.lh()+B0c+a.mh())}
function Pvc(){Kvc();Ovc.call(this,$r($doc,Cvd),Dvd)}
function SEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;return c.text.length}catch(a){return 0}}
function REc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;return -c.move(Evd,-65535)}catch(a){return 0}}
function uXb(a,b){var c,d;c=new Rrc;dfc();Sr(c.e,cbd,4);Orc(c,a);if(b){d=new lnc(rvd);rj(a,new EXb(a,d),(hz(),hz(),gz));rj(a,new HXb(a,d),(Ey(),Ey(),Dy));Orc(c,d)}return c}
function UEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;var d=c.text.length;var e=0;var f=c.duplicate();f.moveEnd(Evd,-1);var g=f.text.length;while(g==d&&f.parentElement()==b&&c.compareEndPoints(Gvd,f)<=0){e+=2;f.moveEnd(Evd,-1);g=f.text.length}return d+e}catch(a){return 0}}
function TEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;var d=c.duplicate();d.moveToElementText(b);d.setEndPoint(Fvd,c);var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(Evd,-1);var i=g.text.length;while(i==e&&g.parentElement()==b){f+=2;g.moveEnd(Evd,-1);i=g.text.length}return e+f}catch(a){return 0}}
function vXb(){var a,b,c,d,e,f;f=new qDc;dfc();Sr(f.e,cbd,5);d=new Nvc;TCc(d.cb,DYc,svd);Cvc(d,(h8(),h8(),g8));b=new Nvc;TCc(b.cb,DYc,tvd);Dvc(b,uvd);Rr(b.cb,nod,true);nDc(f,new qnc(vvd));nDc(f,uXb(d,true));nDc(f,uXb(b,false));c=new Pvc;TCc(c.cb,DYc,wvd);a=new Pvc;TCc(a.cb,DYc,xvd);Dvc(a,uvd);Rr(a.cb,nod,true);nDc(f,new qnc(yvd));nDc(f,uXb(c,true));nDc(f,uXb(a,false));e=new cBc;TCc(e.cb,DYc,zvd);e.cb.rows=5;nDc(f,new qnc(Avd));nDc(f,uXb(e,true));return f}
var vvd='<b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0639\u0627\u062F\u064A:<\/b>',yvd='<br><br><b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0643\u0644\u0645\u0629 \u0627\u0644\u0633\u0631:<\/b>',Avd='<br><br><b>\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u0646\u0635:<\/b>',Kvd='AnyRtlDirectionEstimator',Hvd='CwBasicText$2',Ivd='CwBasicText$3',Fvd='EndToStart',Jvd='PasswordTextBox',Gvd='StartToEnd',Evd='character',wvd='cwBasicText-password',xvd='cwBasicText-password-disabled',zvd='cwBasicText-textarea',svd='cwBasicText-textbox',tvd='cwBasicText-textbox-disabled',Dvd='gwt-PasswordTextBox',Cvd='password',uvd='\u0642\u0631\u0627\u0621\u0629 \u0641\u0642\u0637',Bvd='\u0645\u062E\u062A\u0627\u0631\u0629: ',rvd='\u0645\u062E\u062A\u0627\u0631\u0629: 0, 0';Ywb(434,435,{},i8);_.Ae=function j8(a){return H8((B8(),a))?(WG(),VG):(WG(),UG)};var g8;Ywb(823,1,WWc);_.mc=function CXb(){fAb(this.a,vXb())};Ywb(824,1,DWc,EXb);_.Gc=function FXb(a){wXb(this.b,this.a)};Ywb(825,1,TWc,HXb);_.Ec=function IXb(a){wXb(this.b,this.a)};Ywb(1169,1051,iWc);_.lh=function Fvc(){return REc(this.cb)};_.mh=function Gvc(){return SEc(this.cb)};Ywb(1166,1167,iWc,Pvc);Ywb(1224,1168,iWc);_.lh=function dBc(){return TEc(this.cb)};_.mh=function eBc(){return UEc(this.cb)};var _lb=fLc(afd,Hvd,824),amb=fLc(afd,Ivd,825),Zqb=fLc(ced,Jvd,1166),sgb=fLc(vkd,Kvd,434);IXc(Jn)(18);