function qPb(a){this.b=a}
function tPb(a){this.b=a}
function wPb(a){this.b=a}
function cH(a){MG();return new bH(KG.Td(),a,false)}
function kPb(a,b){if(b==null){Ri(a.d,F2c)}else{Bkc(a.d,b);Ki(a.d,F2c)}}
function lPb(b){var c,d,e;d=(Ccc(),Hr(b.g.db,F_c));if(XIc(d,nVc)){Bkc(b.d,G2c)}else{try{e=dIc(d);c=RG(b.b,e);Bkc(b.d,c);kPb(b,null)}catch(a){a=rvb(a);if(h9(a,143)){kPb(b,H2c)}else throw qvb(a)}}}
function qAb(a){var b,c;b=f9(a.b.je(A2c),147);if(b==null){c=X8(hvb,USc,1,['\u0639\u0634\u0631\u064A','\u0639\u0645\u0644\u0629','\u0639\u0644\u0645\u064A','\u0646\u0633\u0628\u0629 \u0645\u0624\u0648\u064A\u0629','\u062A\u062E\u0635\u064A\u0635']);a.b.le(A2c,c);return c}else{return b}}
function jPb(a){var b,c,d,e,f;b=new Wnc(4,2);Ccc();Rr(b.p,SZc,5);a.f=new sqc;Zi(a.f,B2c);f=qAb(a.c);for(d=0,e=f.length;d<e;++d){c=f[d];nqc(a.f,c)}rj(a.f,new qPb(a),(Xx(),Xx(),Wx));knc(b,0,0,C2c);nnc(b,0,1,a.f);a.e=new dtc;Zi(a.e,B2c);rj(a.e,new tPb(a),(Ky(),Ky(),Jy));nnc(b,1,1,a.e);a.g=new dtc;Zi(a.g,B2c);Vsc(a.g,'31415926535.897932');rj(a.g,new wPb(a),Jy);knc(b,2,0,D2c);nnc(b,2,1,a.g);a.d=new Dkc;Zi(a.d,B2c);knc(b,3,0,E2c);nnc(b,3,1,a.d);mPb(a);return b}
function mPb(b){var c;switch(b.f.db.selectedIndex){case 0:b.b=(MG(),!HG&&(HG=new bH(KG.Ud(),ED((CC(),BC)),false)),MG(),HG);Vsc(b.e,b.b.u);Nfc(b.e,false);break;case 1:b.b=(MG(),!GG&&(GG=cH(ED((CC(),BC)))),MG(),GG);Vsc(b.e,b.b.u);Nfc(b.e,false);break;case 2:b.b=(MG(),!JG&&(JG=new bH(KG.ee(),ED((CC(),BC)),false)),MG(),JG);Vsc(b.e,b.b.u);Nfc(b.e,false);break;case 3:b.b=(MG(),!IG&&(IG=new bH(KG.de(),ED((CC(),BC)),false)),MG(),IG);Vsc(b.e,b.b.u);Nfc(b.e,false);break;case 4:Nfc(b.e,true);c=(Ccc(),Hr(b.e.db,F_c));try{b.b=(MG(),new bH(c,ED((CC(),BC)),true))}catch(a){a=rvb(a);if(h9(a,139)){kPb(b,'\u0646\u0645\u0637 \u063A\u064A\u0631 \u0635\u0627\u0644\u062D');return}else throw qvb(a)}}lPb(b)}
var x2c='#,##0%',y2c='#E0',A2c='cwNumberFormatPatterns',z2c='\xA4#0.00',w2c='\xA4\xA0#0.00;\xA4\xA0#0.00-';var GG,IG,JG;owb(365,1,{});_.Td=function pH(){return w2c};_.de=function BH(){return x2c};_.ee=function CH(){return y2c};owb(366,1,{});_.Td=function GH(){return w2c};_.de=function SH(){return x2c};_.ee=function TH(){return y2c};owb(367,1,{});_.Td=function XH(){return w2c};_.de=function hI(){return x2c};_.ee=function iI(){return y2c};owb(368,1,{});_.Td=function mI(){return w2c};_.de=function yI(){return x2c};_.ee=function zI(){return y2c};owb(369,1,{});_.Td=function DI(){return w2c};_.de=function PI(){return x2c};_.ee=function QI(){return y2c};owb(370,1,{});_.Td=function UI(){return w2c};_.de=function eJ(){return x2c};_.ee=function fJ(){return y2c};owb(371,1,{});_.Td=function jJ(){return w2c};_.de=function vJ(){return x2c};_.ee=function wJ(){return y2c};owb(372,1,{});_.Td=function AJ(){return w2c};_.de=function MJ(){return x2c};_.ee=function NJ(){return y2c};owb(373,1,{});_.Td=function RJ(){return w2c};_.de=function bK(){return x2c};_.ee=function cK(){return y2c};owb(374,1,{});_.Td=function gK(){return w2c};_.de=function sK(){return x2c};_.ee=function tK(){return y2c};owb(375,1,{});_.Td=function xK(){return z2c};_.de=function JK(){return x2c};_.ee=function KK(){return y2c};owb(376,1,{});_.Td=function OK(){return z2c};_.de=function $K(){return x2c};_.ee=function _K(){return y2c};owb(377,1,{});_.Td=function dL(){return w2c};_.de=function pL(){return x2c};_.ee=function qL(){return y2c};owb(378,1,{});_.Td=function uL(){return z2c};_.de=function GL(){return x2c};_.ee=function HL(){return y2c};owb(379,1,{});_.Td=function LL(){return z2c};_.de=function XL(){return x2c};_.ee=function YL(){return y2c};owb(380,1,{});_.Td=function aM(){return z2c};_.de=function mM(){return x2c};_.ee=function nM(){return y2c};owb(715,1,FTc,qPb);_.Cc=function rPb(a){mPb(this.b)};owb(716,1,pTc,tPb);_.Fc=function uPb(a){mPb(this.b)};owb(717,1,pTc,wPb);_.Fc=function xPb(a){lPb(this.b)};owb(718,1,HTc);_.mc=function BPb(){Uyb(this.c,jPb(this.b))};var $jb=THc(O$c,'CwNumberFormat$1',715),_jb=THc(O$c,'CwNumberFormat$2',716),akb=THc(O$c,'CwNumberFormat$3',717);uUc(Jn)(25);