function SJ(a){this.a=a}
function YJ(a){this.b=a}
function BAb(){this.a=new NCc}
function bK(){throw new xwc}
function uJ(b,a){return b.b[EJc+a]}
function cK(a,b){this.a=a;this.b=b}
function Iyb(a,b){this.a=a;this.b=b}
function tJ(a,b){return HV(b,1)?uJ(a,FV(b,1)):null}
function vJ(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[EJc+a[c]]=b[c]}}
function XJ(a){var b;if(a.a>=a.b.a.a.length){throw new QDc}b=a.b.a.a[a.a++];return new cK(b,uJ(a.b.a,b))}
function AAb(a){var b;b=FV(a.a.ke(nkd),159);if(!b){b=new vJ(vV($eb,oFc,1,[afd,Yed,efd,$ed,gfd,cfd,okd,pkd]),vV($eb,oFc,1,[qkd,rkd,skd,tkd,ukd,vkd,wkd,xkd]));a.a.me(nkd,b)}return b}
function Eyb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new BAb;n=new g9b;i=FV(n.j,99);m$b();Sr(n.o,kWc,5);q=Xib(V3);o=new L1b(q);rj(o,new Iyb(a,q),(Dy(),Dy(),Cy));p=new Zac;Sr(p.e,kWc,3);Wac(p,new z6b(hkd));Wac(p,o);a9b(n,0,0,p);Sr(p9b(i,0),F9c,2);g=new Vec;Tr(g.cb,I9c,ikd);MC(g.a);x$b(g.cb,SIc,Xid);Z8b(n,1,0,jkd);a9b(n,1,1,g);k=new Vec;Tr(k.cb,I9c,kkd);MC(k.a);x$b(k.cb,SIc,Xid);Z8b(n,2,0,lkd);a9b(n,2,1,k);b=new fcc;c=AAb(f);for(e=c.je().$b();e.ve();){d=FV(e.we(),160);j=FV(d.ye(),1);r=FV(d.Mc(),1);bcc(b,r,j,-1)}Z8b(n,3,0,mkd);a9b(n,3,1,b);return n}
var mkd='<b>Couleur Pr\xE9f\xE9r\xE9e:<\/b>',lkd='<b>Nom:<\/b>',jkd='<b>Pr\xE9nom:<\/b>',ikd='Amelie',hkd="Cet exemple interagit avec l'\xE9chatillon de l'interface:",Bkd='ConstantMap',Dkd='ConstantMap$1',Ekd='ConstantMap$1$1',Ckd='ConstantMap$EntryImpl',kkd='Crutcher',zkd='CwConstantsExample$1',ykd='ExampleConstants',Akd='ExampleConstants_fr',nkd='colorMap';fgb(364,365,OFc,vJ);_.he=function wJ(a){return (HV(a,1)?uJ(this,FV(a,1)):null)!=null};_.je=function xJ(){return new SJ(this)};_.ke=function yJ(a){return HV(a,1)?uJ(this,FV(a,1)):null};_.oe=function zJ(){return this.a.length};fgb(366,367,QFc,SJ);_.re=function TJ(a){var b,c;if(!HV(a,160)){return false}b=FV(a,160);c=tJ(this.a,b.ye());if(c!=null&&rvc(c,b.Mc())){return true}return false};_.$b=function UJ(){return new YJ(this)};_.oe=function VJ(){return this.a.a.length};fgb(369,1,{},YJ);_.ve=function ZJ(){return this.a<this.b.a.a.length};_.we=function $J(){return XJ(this)};_.xe=function _J(){throw new xwc};_.a=0;fgb(370,1,RFc,cK);_.eQ=function dK(a){var b;if(HV(a,160)){b=FV(a,160);if(rvc(this.a,b.ye())&&rvc(this.b,b.Mc())){return true}}return false};_.ye=function eK(){return this.a};_.Mc=function fK(){return this.b};_.hC=function gK(){var a,b;a=0;b=0;this.a!=null&&(a=Xvc(this.a));this.b!=null&&(b=Xvc(this.b));return a^b};_.ze=function hK(a){return bK(FV(a,1))};_.tS=function iK(){return this.a+KLc+this.b};fgb(659,1,_Fc,Iyb);_.Ec=function Jyb(a){Qib(this.a,this.b+yjd)};fgb(660,1,cGc);_.mc=function Nyb(){ojb(this.b,Eyb(this.a))};fgb(685,1,{},BAb);var V3=puc(C$c,ykd),s3=nuc(C$c,zkd,659),U3=nuc(C$c,Akd,685),j_=nuc(q2c,Bkd,364),i_=nuc(q2c,Ckd,370),h_=nuc(q2c,Dkd,366),g_=nuc(q2c,Ekd,369);QGc(Jn)(30);