function Lcc(){Mcc.call(this,false)}
function kdc(a,b){mdc.call(this,a,false);this.b=b}
function ldc(a,b){mdc.call(this,a,false);jdc(this,b)}
function ndc(a){mdc.call(this,fcd,true);jdc(this,a)}
function UAb(a){this.c=a;this.b=Mkb(this.c.a)}
function pcc(a,b){return wcc(a,b,a.a.b)}
function Pb(a,b){_b((le(),ge),a,vV(Veb,nFc,135,[(Utc(),b?Ttc:Stc)]))}
function jdc(a,b){a.d=b;!!a.c&&Kcc(a.c,a);if(b){Vr(b.cb,-1);Bf();Pb(a.cb,true)}else{Bf();Pb(a.cb,false)}}
function wcc(a,b,c){if(c<0||c>a.a.b){throw new Ltc}a.o&&(m$b(),Sr(b.cb,F9c,2));occ(a,c,b.cb);nAc(a.a,c,b);return b}
function qdc(){var a;Ui(this,(m$b(),qs($doc,iWc)));jj(this.cb,gcd);a=qs($doc,cJc);n$b(this.cb,a);Tr(a,TIc,hcd)}
function Jkb(a){var b,c;b=FV(a.a.ke(Jbd),149);if(b==null){c=vV($eb,oFc,1,[Kbd,Lbd,Mbd]);a.a.me(Jbd,c);return c}else{return b}}
function Lkb(a){var b,c;b=FV(a.a.ke(Rbd),149);if(b==null){c=vV($eb,oFc,1,[Sbd,Tbd,Ubd]);a.a.me(Rbd,c);return c}else{return b}}
function Kkb(a){var b,c;b=FV(a.a.ke(Nbd),149);if(b==null){c=vV($eb,oFc,1,[Obd,Pbd,sQc,Qbd]);a.a.me(Nbd,c);return c}else{return b}}
function Hkb(a){var b,c;b=FV(a.a.ke(xbd),149);if(b==null){c=vV($eb,oFc,1,[ybd,zbd,Abd,Bbd,Cbd]);a.a.me(xbd,c);return c}else{return b}}
function Ikb(a){var b,c;b=FV(a.a.ke(Dbd),149);if(b==null){c=vV($eb,oFc,1,[Ebd,Fbd,Gbd,Hbd,Ibd]);a.a.me(Dbd,c);return c}else{return b}}
function Mkb(a){var b,c;b=FV(a.a.ke(Vbd),149);if(b==null){c=vV($eb,oFc,1,[Wbd,Xbd,Ybd,Zbd,$bd,_bd]);a.a.me(Vbd,c);return c}else{return b}}
function QAb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q;o=new UAb(a);n=new Lcc;n.b=true;x$b(n.cb,SIc,acd);n.e=true;q=new Mcc(true);p=Jkb(a.a);for(k=0;k<p.length;++k){ncc(q,new kdc(p[k],o))}d=new Mcc(true);d.e=true;ncc(n,new ldc(bcd,d));e=Ikb(a.a);for(k=0;k<e.length;++k){if(k==3){pcc(d,new qdc);ncc(d,new ldc(e[3],q));pcc(d,new qdc)}else{ncc(d,new kdc(e[k],o))}}b=new Mcc(true);ncc(n,new ldc(ccd,b));c=Hkb(a.a);for(k=0;k<c.length;++k){ncc(b,new kdc(c[k],o))}f=new Mcc(true);ncc(n,new ndc(f));g=Kkb(a.a);for(k=0;k<g.length;++k){ncc(f,new kdc(g[k],o))}i=new Mcc(true);pcc(n,new qdc);ncc(n,new ldc(dcd,i));j=Lkb(a.a);for(k=0;k<j.length;++k){ncc(i,new kdc(j[k],o))}_lc(n.cb,LHc,ecd);Jcc(n,ecd);return n}
var acd='500px',dcd='Aide',Tbd='Biscuit de fortune',Cbd='Coller',Lbd='Comment apprivoiser un perroquet sauvage',Sbd='Contenu',Bbd='Copier',Abd='Couper',icd='CwMenuBar$1',Zbd="Essayez quelque chose d'autre",Pbd='Exemples',bcd='Fichier',fcd='GWT',Qbd='GWiTtez avec le programme',Mbd="L'\xE9levage des \xE9meus pour les nuls",jcd='MenuItemSeparator',Wbd="Merci d'avoir s\xE9lectionn\xE9 une option de menu",Ybd="N'avez-vous rien de mieux \xE0 faire que de s\xE9lectionner des options de menu?",Ebd='Nouveau',Fbd='Ouvrir',Kbd='P\xEAcher dans le d\xE9sert.txt',Ibd='Quitter',Hbd='R\xE9cent',zbd='R\xE9tablir',Obd='T\xE9l\xE9charger',_bd='Un autre clic gaspill\xE9',Xbd='Une s\xE9lection vraiment pertinente',$bd="ceci n'est qu'un menu!",ecd='cwMenuBar',xbd='cwMenuBarEditOptions',Dbd='cwMenuBarFileOptions',Jbd='cwMenuBarFileRecents',Nbd='cwMenuBarGWTOptions',Rbd='cwMenuBarHelpOptions',Vbd='cwMenuBarPrompts',gcd='gwt-MenuItemSeparator',hcd='menuSeparatorInner',Ubd='\xC0 propos de GWT',ccd='\xC9dition';fgb(691,1,{},UAb);_.oc=function VAb(){d_b(this.b[this.a]);this.a=(this.a+1)%this.b.length};_.a=0;fgb(692,1,cGc);_.mc=function ZAb(){ojb(this.b,QAb(this.a))};fgb(1090,102,qFc,Lcc);fgb(1097,103,{100:1,105:1,119:1},kdc,ldc,ndc);fgb(1098,103,{100:1,106:1,119:1},qdc);var $3=nuc(EZc,icd,691),S9=nuc(kZc,jcd,1098);QGc(Jn)(7);