function OG(a){this.a=a}
function UG(a){this.b=a}
function Inb(){this.a=new Qpc}
function ZG(){throw new Ajc}
function qG(b,a){return b.b[Hwc+a]}
function $G(a,b){this.a=a;this.b=b}
function Plb(a,b){this.a=a;this.b=b}
function pG(a,b){return gJ(b,1)?qG(a,eJ(b,1)):null}
function rG(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[Hwc+a[c]]=b[c]}}
function TG(a){var b;if(a.a>=a.b.a.a.length){throw new Tqc}b=a.b.a.a[a.a++];return new $G(b,qG(a.b.a,b))}
function Hnb(a){var b;b=eJ(a.a.hd(n7c),159);if(!b){b=new rG(WI(f2,rsc,1,[b2c,Z1c,f2c,_1c,h2c,d2c,o7c,p7c]),WI(f2,rsc,1,[eWc,q7c,r7c,s7c,dWc,gWc,t7c,u7c]));a.a.kd(n7c,b)}return b}
function Llb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new Inb;n=new mYb;i=eJ(n.j,99);sNb();Sr(n.o,nJc,5);q=c6(aT);o=new RQb(q);rj(o,new Plb(a,q),(Dy(),Dy(),Cy));p=new d$b;Sr(p.e,nJc,3);a$b(p,new FVb(U6c));a$b(p,o);gYb(n,0,0,p);Sr(vYb(i,0),HYc,2);g=new _1b;Tr(g.cb,KYc,i7c);MC(g.a);DNb(g.cb,Vvc,Q5c);dYb(n,1,0,j7c);gYb(n,1,1,g);k=new _1b;Tr(k.cb,KYc,k7c);MC(k.a);DNb(k.cb,Vvc,Q5c);dYb(n,2,0,l7c);gYb(n,2,1,k);b=new l_b;c=Hnb(f);for(e=c.gd().$b();e.td();){d=eJ(e.ud(),160);j=eJ(d.wd(),1);r=eJ(d.Mc(),1);h_b(b,r,j,-1)}dYb(n,3,0,m7c);gYb(n,3,1,b);return n}
var l7c='<b>\u53BB\u5E74\u540D\u79F0\uFF1A<\/b>',j7c='<b>\u540D\u5B57\uFF1A<\/b>',m7c='<b>\u6700\u559C\u7231\u7684\u989C\u8272\uFF1A<\/b>',i7c='Amelie',y7c='ConstantMap',A7c='ConstantMap$1',B7c='ConstantMap$1$1',z7c='ConstantMap$EntryImpl',k7c='Crutcher',w7c='CwConstantsExample$1',v7c='ExampleConstants',x7c='ExampleConstants_zh',n7c='colorMap';m3(354,355,Rsc,rG);_.ed=function sG(a){return (gJ(a,1)?qG(this,eJ(a,1)):null)!=null};_.gd=function tG(){return new OG(this)};_.hd=function uG(a){return gJ(a,1)?qG(this,eJ(a,1)):null};_.md=function vG(){return this.a.length};m3(356,357,Tsc,OG);_.pd=function PG(a){var b,c;if(!gJ(a,160)){return false}b=eJ(a,160);c=pG(this.a,b.wd());if(c!=null&&uic(c,b.Mc())){return true}return false};_.$b=function QG(){return new UG(this)};_.md=function RG(){return this.a.a.length};m3(359,1,{},UG);_.td=function VG(){return this.a<this.b.a.a.length};_.ud=function WG(){return TG(this)};_.vd=function XG(){throw new Ajc};_.a=0;m3(360,1,Usc,$G);_.eQ=function _G(a){var b;if(gJ(a,160)){b=eJ(a,160);if(uic(this.a,b.wd())&&uic(this.b,b.Mc())){return true}}return false};_.wd=function aH(){return this.a};_.Mc=function bH(){return this.b};_.hC=function cH(){var a,b;a=0;b=0;this.a!=null&&(a=$ic(this.a));this.b!=null&&(b=$ic(this.b));return a^b};_.xd=function dH(a){return ZG(eJ(a,1))};_.tS=function eH(){return this.a+Nyc+this.b};m3(638,1,ctc,Plb);_.Ec=function Qlb(a){X5(this.a,this.b+v6c)};m3(639,1,ftc);_.mc=function Ulb(){v6(this.b,Llb(this.a))};m3(664,1,{},Inb);var aT=shc(FNc,v7c),zS=qhc(FNc,w7c,638),_S=qhc(FNc,x7c,664),BO=qhc(tRc,y7c,354),AO=qhc(tRc,z7c,360),zO=qhc(tRc,A7c,356),yO=qhc(tRc,B7c,359);Ttc(Jn)(30);