function vG(a){this.a=a}
function BG(a){this.b=a}
function vmb(){this.a=new inc}
function GG(){throw new Ugc}
function ZF(b,a){return b.b[Ysc+a]}
function HG(a,b){this.a=a;this.b=b}
function Ckb(a,b){this.a=a;this.b=b}
function YF(a,b){return PI(b,1)?ZF(a,NI(b,1)):null}
function $F(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[Ysc+a[c]]=b[c]}}
function AG(a){var b;if(a.a>=a.b.a.a.length){throw new loc}b=a.b.a.a[a.a++];return new HG(b,ZF(a.b.a,b))}
function umb(a){var b;b=NI(a.a.gd(iBc),158);if(!b){b=new $F(DI(G1,Lpc,1,[kzc,hzc,nzc,jzc,ozc,mzc,jBc,kBc]),DI(G1,Lpc,1,[Rxc,lBc,mBc,nBc,Qxc,Sxc,oBc,pBc]));a.a.jd(iBc,b)}return b}
function ykb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new vmb;n=new $Vb;i=NI(n.j,98);iLb();Sr(n.o,pwc,5);q=d5(GS);o=new FOb(q);rj(o,new Ckb(a,q),(ky(),ky(),jy));p=new RXb;Sr(p.e,pwc,3);OXb(p,new tTb(fBc));OXb(p,o);UVb(n,0,0,p);Sr(hWb(i,0),fyc,2);g=new K_b;Tr(g.cb,gyc,'Amelie');tC(g.a);sLb(g.cb,Fsc,WAc);RVb(n,1,0,'<b>\u540D\u5B57\uFF1A<\/b>');UVb(n,1,1,g);k=new K_b;Tr(k.cb,gyc,'Crutcher');tC(k.a);sLb(k.cb,Fsc,WAc);RVb(n,2,0,'<b>\u53BB\u5E74\u540D\u79F0\uFF1A<\/b>');UVb(n,2,1,k);b=new ZYb;c=umb(f);for(e=c.fd().Zb();e.sd();){d=NI(e.td(),159);j=NI(d.vd(),1);r=NI(d.Lc(),1);VYb(b,r,j,-1)}RVb(n,3,0,'<b>\u6700\u559C\u7231\u7684\u989C\u8272\uFF1A<\/b>');UVb(n,3,1,b);return n}
var iBc='colorMap';N2(354,355,jqc,$F);_.dd=function _F(a){return (PI(a,1)?ZF(this,NI(a,1)):null)!=null};_.fd=function aG(){return new vG(this)};_.gd=function bG(a){return PI(a,1)?ZF(this,NI(a,1)):null};_.ld=function cG(){return this.a.length};N2(356,357,lqc,vG);_.od=function wG(a){var b,c;if(!PI(a,159)){return false}b=NI(a,159);c=YF(this.a,b.vd());if(c!=null&&Ofc(c,b.Lc())){return true}return false};_.Zb=function xG(){return new BG(this)};_.ld=function yG(){return this.a.a.length};N2(359,1,{},BG);_.sd=function CG(){return this.a<this.b.a.a.length};_.td=function DG(){return AG(this)};_.ud=function EG(){throw new Ugc};_.a=0;N2(360,1,mqc,HG);_.eQ=function IG(a){var b;if(PI(a,159)){b=NI(a,159);if(Ofc(this.a,b.vd())&&Ofc(this.b,b.Lc())){return true}}return false};_.vd=function JG(){return this.a};_.Lc=function KG(){return this.b};_.hC=function LG(){var a,b;a=0;b=0;this.a!=null&&(a=sgc(this.a));this.b!=null&&(b=sgc(this.b));return a^b};_.wd=function MG(a){return GG(NI(a,1))};_.tS=function NG(){return this.a+Jtc+this.b};N2(635,1,vqc,Ckb);_.Dc=function Dkb(a){Y4(this.a,this.b+dBc)};N2(636,1,yqc);_.lc=function Hkb(){w5(this.b,ykb(this.a))};N2(661,1,{},vmb);var GS=Mec(mxc,'ExampleConstants'),dS=Kec(mxc,'CwConstantsExample$1',635),FS=Kec(mxc,'ExampleConstants_zh',661),iO=Kec(Bxc,'ConstantMap',354),hO=Kec(Bxc,'ConstantMap$EntryImpl',360),gO=Kec(Bxc,'ConstantMap$1',356),fO=Kec(Bxc,'ConstantMap$1$1',359);lrc(Jn)(30);