function uP(a){this.a=a}
function AP(a){this.b=a}
function N2b(){this.a=new W4c}
function FP(){throw new G$c}
function GP(a,b){this.a=a;this.b=b}
function U0b(a,b){this.a=a;this.b=b}
function YO(b,a){return b.b[Nbd+a]}
function XO(a,b){return Lmb(b,1)?YO(a,Jmb(b,1)):null}
function ZO(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[Nbd+a[c]]=b[c]}}
function zP(a){var b;if(a.a>=a.b.a.a.length){throw new Z5c}b=a.b.a.a[a.a++];return new GP(b,YO(a.b.a,b))}
function M2b(a){var b;b=Jmb(a.a.ke(kOd),159);if(!b){b=new ZO(zmb(kJb,x7c,1,[kBd,fJd,lBd,hJd,jBd,mBd,lOd,mOd]),zmb(kJb,x7c,1,[iJd,eJd,kJd,gJd,lJd,jJd,nOd,oOd]));a.a.me(kOd,b)}return b}
function Q0b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new N2b;n=new sDc;i=Jmb(n.j,99);ysc();Sr(n.o,tod,5);q=hNb(fyb);o=new Xvc(q);rj(o,new U0b(a,q),(Dy(),Dy(),Cy));p=new jFc;Sr(p.e,tod,3);gFc(p,new LAc(nNd));gFc(p,o);mDc(n,0,0,p);Sr(BDc(i,0),ODd,2);g=new fJc;Tr(g.cb,RDd,fOd);MC(g.a);Jsc(g.cb,_ad,$Md);jDc(n,1,0,gOd);mDc(n,1,1,g);k=new fJc;Tr(k.cb,RDd,hOd);MC(k.a);Jsc(k.cb,_ad,$Md);jDc(n,2,0,iOd);mDc(n,2,1,k);b=new rGc;c=M2b(f);for(e=c.je().$b();e.ve();){d=Jmb(e.we(),160);j=Jmb(d.ye(),1);r=Jmb(d.Mc(),1);nGc(b,r,j,-1)}jDc(n,3,0,jOd);mDc(n,3,1,b);return n}
var jOd='<b>Favorite color:<\/b>',gOd='<b>First Name:<\/b>',iOd='<b>Last Name:<\/b>',fOd='Amelie',sOd='ConstantMap',uOd='ConstantMap$1',vOd='ConstantMap$1$1',tOd='ConstantMap$EntryImpl',hOd='Crutcher',qOd='CwConstantsExample$1',pOd='ExampleConstants',rOd='ExampleConstants_',kOd='colorMap';rKb(393,394,X7c,ZO);_.he=function $O(a){return (Lmb(a,1)?YO(this,Jmb(a,1)):null)!=null};_.je=function _O(){return new uP(this)};_.ke=function aP(a){return Lmb(a,1)?YO(this,Jmb(a,1)):null};_.oe=function bP(){return this.a.length};rKb(395,396,Z7c,uP);_.re=function vP(a){var b,c;if(!Lmb(a,160)){return false}b=Jmb(a,160);c=XO(this.a,b.ye());if(c!=null&&AZc(c,b.Mc())){return true}return false};_.$b=function wP(){return new AP(this)};_.oe=function xP(){return this.a.a.length};rKb(398,1,{},AP);_.ve=function BP(){return this.a<this.b.a.a.length};_.we=function CP(){return zP(this)};_.xe=function DP(){throw new G$c};_.a=0;rKb(399,1,$7c,GP);_.eQ=function HP(a){var b;if(Lmb(a,160)){b=Jmb(a,160);if(AZc(this.a,b.ye())&&AZc(this.b,b.Mc())){return true}}return false};_.ye=function IP(){return this.a};_.Mc=function JP(){return this.b};_.hC=function KP(){var a,b;a=0;b=0;this.a!=null&&(a=e$c(this.a));this.b!=null&&(b=e$c(this.b));return a^b};_.ze=function LP(a){return FP(Jmb(a,1))};_.tS=function MP(){return this.a+Tdd+this.b};rKb(721,1,i8c,U0b);_.Ec=function V0b(a){aNb(this.a,this.b+BNd)};rKb(722,1,l8c);_.mc=function Z0b(){ANb(this.b,Q0b(this.a))};rKb(747,1,{},N2b);var fyb=yYc(Lsd,pOd),Exb=wYc(Lsd,qOd,721),eyb=wYc(Lsd,rOd,747),Qsb=wYc(zwd,sOd,393),Psb=wYc(zwd,tOd,399),Osb=wYc(zwd,uOd,395),Nsb=wYc(zwd,vOd,398);Z8c(Jn)(30);