function Wyb(a){this.a=a}
function Zyb(a){this.a=a}
function azb(a){this.a=a}
function SG(a){AG();return new RG(yG.Td(),a,false)}
function Qyb(a,b){if(b==null){Ri(a.c,rOc)}else{p4b(a.c,b);Ki(a.c,rOc)}}
function Wjb(a){var b,c;b=wV(a.a.je(mOc),148);if(b==null){c=mV(Ieb,SCc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.a.le(mOc,c);return c}else{return b}}
function Ryb(b){var c,d,e;d=(zYb(),Hr(b.f.cb,qLc));if(Vsc(d,lFc)){p4b(b.c,sOc)}else{try{e=bsc(d);c=FG(b.a,e);p4b(b.c,c);Qyb(b,null)}catch(a){a=Seb(a);if(yV(a,144)){Qyb(b,tOc)}else throw Reb(a)}}}
function Pyb(a){var b,c,d,e,f;b=new G7b(4,2);zYb();Rr(b.o,AJc,5);a.e=new cac;Zi(a.e,nOc);f=Wjb(a.b);for(d=0,e=f.length;d<e;++d){c=f[d];Z9b(a.e,c)}qj(a.e,new Wyb(a),(ky(),ky(),jy));W6b(b,0,0,oOc);Z6b(b,0,1,a.e);a.d=new Pcc;Zi(a.d,nOc);qj(a.d,new Zyb(a),(Zy(),Zy(),Yy));Z6b(b,1,1,a.d);a.f=new Pcc;Zi(a.f,nOc);Fcc(a.f,'31415926535.897932');qj(a.f,new azb(a),Yy);W6b(b,2,0,pOc);Z6b(b,2,1,a.f);a.c=new r4b;Zi(a.c,nOc);W6b(b,3,0,qOc);Z6b(b,3,1,a.c);Syb(a);return b}
function Syb(b){var c;switch(b.e.cb.selectedIndex){case 0:b.a=(AG(),!vG&&(vG=new RG(yG.Ud(),sD((SC(),RC)),false)),AG(),vG);Fcc(b.d,b.a.t);B_b(b.d,false);break;case 1:b.a=(AG(),!uG&&(uG=SG(sD((SC(),RC)))),AG(),uG);Fcc(b.d,b.a.t);B_b(b.d,false);break;case 2:b.a=(AG(),!xG&&(xG=new RG(yG.ee(),sD((SC(),RC)),false)),AG(),xG);Fcc(b.d,b.a.t);B_b(b.d,false);break;case 3:b.a=(AG(),!wG&&(wG=new RG(yG.de(),sD((SC(),RC)),false)),AG(),wG);Fcc(b.d,b.a.t);B_b(b.d,false);break;case 4:B_b(b.d,true);c=(zYb(),Hr(b.d.cb,qLc));try{b.a=(AG(),new RG(c,sD((SC(),RC)),true))}catch(a){a=Seb(a);if(yV(a,140)){Qyb(b,uOc);return}else throw Reb(a)}}Ryb(b)}
var jOc='#,##0.00\xA0\xA4',kOc='#,##0\xA0%',lOc='#E0',mOc='cwNumberFormatPatterns';var uG,wG,xG;Pfb(357,1,{});_.Td=function dH(){return jOc};_.de=function pH(){return kOc};_.ee=function qH(){return lOc};Pfb(358,1,{});_.Td=function uH(){return jOc};_.de=function GH(){return kOc};_.ee=function HH(){return lOc};Pfb(359,1,{});_.Td=function LH(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.de=function XH(){return kOc};_.ee=function YH(){return lOc};Pfb(360,1,{});_.Td=function aI(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.de=function mI(){return kOc};_.ee=function nI(){return lOc};Pfb(361,1,{});_.Td=function rI(){return jOc};_.de=function DI(){return kOc};_.ee=function EI(){return lOc};Pfb(362,1,{});_.Td=function II(){return jOc};_.de=function UI(){return kOc};_.ee=function VI(){return lOc};Pfb(673,1,DDc,Wyb);_.Cc=function Xyb(a){Syb(this.a)};Pfb(674,1,nDc,Zyb);_.Fc=function $yb(a){Syb(this.a)};Pfb(675,1,nDc,azb);_.Fc=function bzb(a){Ryb(this.a)};Pfb(676,1,FDc);_.lc=function fzb(){yib(this.b,Pyb(this.a))};var y3=Rrc(yKc,'CwNumberFormat$1',673),z3=Rrc(yKc,'CwNumberFormat$2',674),A3=Rrc(yKc,'CwNumberFormat$3',675);sEc(In)(25);