function i8(){}
function Bvc(a,b){OC(a.a,b)}
function EXb(a,b){this.b=a;this.a=b}
function HXb(a,b){this.b=a;this.a=b}
function H8(a){return oyb(s8,a)}
function h8(){h8=_Vc;g8=new i8}
function wXb(a,b){hnc(b,Avd+a.lh()+A0c+a.mh())}
function Ovc(){Jvc();Nvc.call(this,$r($doc,Bvd),Cvd)}
function REc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;return c.text.length}catch(a){return 0}}
function QEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;return -c.move(Dvd,-65535)}catch(a){return 0}}
function uXb(a,b){var c,d;c=new Qrc;dfc();Sr(c.e,bbd,4);Nrc(c,a);if(b){d=new lnc(qvd);rj(a,new EXb(a,d),(hz(),hz(),gz));rj(a,new HXb(a,d),(Ey(),Ey(),Dy));Nrc(c,d)}return c}
function TEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;var d=c.text.length;var e=0;var f=c.duplicate();f.moveEnd(Dvd,-1);var g=f.text.length;while(g==d&&f.parentElement()==b&&c.compareEndPoints(Fvd,f)<=0){e+=2;f.moveEnd(Dvd,-1);g=f.text.length}return d+e}catch(a){return 0}}
function SEc(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;var d=c.duplicate();d.moveToElementText(b);d.setEndPoint(Evd,c);var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(Dvd,-1);var i=g.text.length;while(i==e&&g.parentElement()==b){f+=2;g.moveEnd(Dvd,-1);i=g.text.length}return e+f}catch(a){return 0}}
function vXb(){var a,b,c,d,e,f;f=new pDc;dfc();Sr(f.e,bbd,5);d=new Mvc;SCc(d.cb,CYc,rvd);Bvc(d,(h8(),h8(),g8));b=new Mvc;SCc(b.cb,CYc,svd);Cvc(b,tvd);Rr(b.cb,mod,true);mDc(f,new qnc(uvd));mDc(f,uXb(d,true));mDc(f,uXb(b,false));c=new Ovc;SCc(c.cb,CYc,vvd);a=new Ovc;SCc(a.cb,CYc,wvd);Cvc(a,tvd);Rr(a.cb,mod,true);mDc(f,new qnc(xvd));mDc(f,uXb(c,true));mDc(f,uXb(a,false));e=new bBc;SCc(e.cb,CYc,yvd);e.cb.rows=5;mDc(f,new qnc(zvd));mDc(f,uXb(e,true));return f}
var uvd='<b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0639\u0627\u062F\u064A:<\/b>',xvd='<br><br><b>\u0645\u0631\u0628\u0639 \u0646\u0635 \u0643\u0644\u0645\u0629 \u0627\u0644\u0633\u0631:<\/b>',zvd='<br><br><b>\u0645\u0646\u0637\u0642\u0629 \u0627\u0644\u0646\u0635:<\/b>',Jvd='AnyRtlDirectionEstimator',Gvd='CwBasicText$2',Hvd='CwBasicText$3',Evd='EndToStart',Ivd='PasswordTextBox',Fvd='StartToEnd',Dvd='character',vvd='cwBasicText-password',wvd='cwBasicText-password-disabled',yvd='cwBasicText-textarea',rvd='cwBasicText-textbox',svd='cwBasicText-textbox-disabled',Cvd='gwt-PasswordTextBox',Bvd='password',tvd='\u0642\u0631\u0627\u0621\u0629 \u0641\u0642\u0637',Avd='\u0645\u062E\u062A\u0627\u0631\u0629: ',qvd='\u0645\u062E\u062A\u0627\u0631\u0629: 0, 0';Ywb(434,435,{},i8);_.Ae=function j8(a){return H8((B8(),a))?(WG(),VG):(WG(),UG)};var g8;Ywb(823,1,VWc);_.mc=function CXb(){fAb(this.a,vXb())};Ywb(824,1,CWc,EXb);_.Gc=function FXb(a){wXb(this.b,this.a)};Ywb(825,1,SWc,HXb);_.Ec=function IXb(a){wXb(this.b,this.a)};Ywb(1169,1051,hWc);_.lh=function Evc(){return QEc(this.cb)};_.mh=function Fvc(){return REc(this.cb)};Ywb(1166,1167,hWc,Ovc);Ywb(1224,1168,hWc);_.lh=function cBc(){return SEc(this.cb)};_.mh=function dBc(){return TEc(this.cb)};var _lb=eLc(_ed,Gvd,824),amb=eLc(_ed,Hvd,825),Zqb=eLc(bed,Ivd,1166),sgb=eLc(ukd,Jvd,434);HXc(Jn)(18);