function zyb(a){this.b=a}
function Cyb(a){this.b=a}
function Fyb(a){this.b=a}
function BG(a){jG();return new AG(hG.Td(),a,false)}
function tyb(a,b){if(b==null){Ri(a.d,GNc)}else{K3b(a.d,b);Ki(a.d,GNc)}}
function zjb(a){var b,c;b=fV(a.b.je(BNc),147);if(b==null){c=XU(qeb,bCc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.b.le(BNc,c);return c}else{return b}}
function uyb(b){var c,d,e;d=(LXb(),Hr(b.g.db,FKc));if(esc(d,wEc)){K3b(b.d,HNc)}else{try{e=mrc(d);c=oG(b.b,e);K3b(b.d,c);tyb(b,null)}catch(a){a=Aeb(a);if(hV(a,143)){tyb(b,INc)}else throw zeb(a)}}}
function syb(a){var b,c,d,e,f;b=new d7b(4,2);LXb();Rr(b.p,RIc,5);a.f=new B9b;Zi(a.f,CNc);f=zjb(a.c);for(d=0,e=f.length;d<e;++d){c=f[d];w9b(a.f,c)}rj(a.f,new zyb(a),(Wx(),Wx(),Vx));t6b(b,0,0,DNc);w6b(b,0,1,a.f);a.e=new mcc;Zi(a.e,CNc);rj(a.e,new Cyb(a),(Jy(),Jy(),Iy));w6b(b,1,1,a.e);a.g=new mcc;Zi(a.g,CNc);ccc(a.g,'31415926535.897932');rj(a.g,new Fyb(a),Iy);t6b(b,2,0,ENc);w6b(b,2,1,a.g);a.d=new M3b;Zi(a.d,CNc);t6b(b,3,0,FNc);w6b(b,3,1,a.d);vyb(a);return b}
function vyb(b){var c;switch(b.f.db.selectedIndex){case 0:b.b=(jG(),!eG&&(eG=new AG(hG.Ud(),bD((BC(),AC)),false)),jG(),eG);ccc(b.e,b.b.u);W$b(b.e,false);break;case 1:b.b=(jG(),!dG&&(dG=BG(bD((BC(),AC)))),jG(),dG);ccc(b.e,b.b.u);W$b(b.e,false);break;case 2:b.b=(jG(),!gG&&(gG=new AG(hG.ee(),bD((BC(),AC)),false)),jG(),gG);ccc(b.e,b.b.u);W$b(b.e,false);break;case 3:b.b=(jG(),!fG&&(fG=new AG(hG.de(),bD((BC(),AC)),false)),jG(),fG);ccc(b.e,b.b.u);W$b(b.e,false);break;case 4:W$b(b.e,true);c=(LXb(),Hr(b.e.db,FKc));try{b.b=(jG(),new AG(c,bD((BC(),AC)),true))}catch(a){a=Aeb(a);if(hV(a,139)){tyb(b,JNc);return}else throw zeb(a)}}uyb(b)}
var yNc='#,##0.00\xA0\xA4',zNc='#,##0\xA0%',ANc='#E0',BNc='cwNumberFormatPatterns';var dG,fG,gG;xfb(355,1,{});_.Td=function OG(){return yNc};_.de=function $G(){return zNc};_.ee=function _G(){return ANc};xfb(356,1,{});_.Td=function dH(){return yNc};_.de=function pH(){return zNc};_.ee=function qH(){return ANc};xfb(357,1,{});_.Td=function uH(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.de=function GH(){return zNc};_.ee=function HH(){return ANc};xfb(358,1,{});_.Td=function LH(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.de=function XH(){return zNc};_.ee=function YH(){return ANc};xfb(359,1,{});_.Td=function aI(){return yNc};_.de=function mI(){return zNc};_.ee=function nI(){return ANc};xfb(360,1,{});_.Td=function rI(){return yNc};_.de=function DI(){return zNc};_.ee=function EI(){return ANc};xfb(670,1,OCc,zyb);_.Cc=function Ayb(a){vyb(this.b)};xfb(671,1,yCc,Cyb);_.Fc=function Dyb(a){vyb(this.b)};xfb(672,1,yCc,Fyb);_.Fc=function Gyb(a){uyb(this.b)};xfb(673,1,QCc);_.mc=function Kyb(){bib(this.c,syb(this.b))};var h3=arc(NJc,'CwNumberFormat$1',670),i3=arc(NJc,'CwNumberFormat$2',671),j3=arc(NJc,'CwNumberFormat$3',672);DDc(Jn)(25);