function r6b(){}
function v6b(){}
function k6b(a,b){a.b=b}
function l6b(a){if(a==a6b){return true}pG();return a==d6b}
function m6b(a){if(a==_5b){return true}pG();return a==$5b}
function t6b(a){this.b=(i8b(),d8b).a;this.d=(p8b(),o8b).a;this.a=a}
function i6b(a,b){var c;c=wV(a.ab,96);c.b=b.a;!!c.c&&h0b(c.c,b)}
function j6b(a,b){var c;c=wV(a.ab,96);c.d=b.a;!!c.c&&JYb(c.c,vJc,b.a)}
function e6b(){e6b=ICc;Z5b=new r6b;a6b=new r6b;_5b=new r6b;$5b=new r6b;b6b=new r6b;c6b=new r6b;d6b=new r6b}
function n6b(){e6b();j0b.call(this);this.b=(i8b(),d8b);this.c=(p8b(),o8b);zYb();Rr(this.e,wJc,0);Rr(this.e,xJc,0)}
function f6b(a,b,c){var d;if(c==Z5b){if(b==a.a){return}else if(a.a){throw new bsc('Only one CENTER widget may be added')}}xj(b);pkc(a.j,b);c==Z5b&&(a.a=b);d=new t6b(c);b.ab=d;i6b(b,a.b);j6b(b,a.c);h6b(a);zj(b,a)}
function g6b(a,b){var c,d,e,f,g,i,j;Ojc(a.cb,hFc,b);i=new lAc;j=new Akc(a.j);while(j.b<j.c.c){c=ykc(j);g=wV(c.ab,96).a;e=wV(i.je(g),142);d=!e?1:e.a;f=g==b6b?'north'+d:g==c6b?'south'+d:g==d6b?'west'+d:g==$5b?'east'+d:g==a6b?'linestart'+d:g==_5b?'lineend'+d:oJc;Ojc((zYb(),js(c.cb)),b,f);i.le(g,rsc(d+1))}}
function h6b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t;b=a.d;while((zYb(),b.children.length)>0){xr(b,b.children[0])}q=1;e=1;for(i=new Akc(a.j);i.b<i.c.c;){d=ykc(i);f=wV(d.ab,96).a;f==b6b||f==c6b?++q:(f==$5b||f==d6b||f==a6b||f==_5b)&&++e}r=lV(xeb,NCc,97,q,0);for(g=0;g<q;++g){r[g]=new v6b;r[g].b=qs($doc,tJc);AYb(b,r[g].b)}k=0;n=e-1;o=0;s=q-1;c=null;for(i=new Akc(a.j);i.b<i.c.c;){d=ykc(i);j=wV(d.ab,96);t=qs($doc,uJc);j.c=t;Sr(j.c,hJc,j.b);JYb(j.c,vJc,j.d);Sr(j.c,IFc,hFc);Sr(j.c,HFc,hFc);if(j.a==b6b){CYb(r[o].b,t,r[o].a);AYb(t,d.cb);Rr(t,lLc,n-k+1);++o}else if(j.a==c6b){CYb(r[s].b,t,r[s].a);AYb(t,d.cb);Rr(t,lLc,n-k+1);--s}else if(j.a==Z5b){c=t}else if(l6b(j.a)){p=r[o];CYb(p.b,t,p.a++);AYb(t,d.cb);Rr(t,kMc,s-o+1);++k}else if(m6b(j.a)){p=r[o];CYb(p.b,t,p.a);AYb(t,d.cb);Rr(t,kMc,s-o+1);--n}}if(a.a){p=r[o];CYb(p.b,c,p.a);AYb(c,a.a.cb)}}
Pfb(747,1,BDc);_.lc=function CDb(){var a,b,c;yib(this.a,(a=new n6b,ij(a.cb,'cw-DockPanel'),zYb(),Rr(a.e,wJc,4),k6b(a,(i8b(),c8b)),f6b(a,new y4b(cMc),(e6b(),b6b)),f6b(a,new y4b(dMc),c6b),f6b(a,new y4b(eMc),$5b),f6b(a,new y4b(fMc),d6b),f6b(a,new y4b(gMc),b6b),f6b(a,new y4b(hMc),c6b),b=new y4b("Voici un <code>panneau de d\xE9filement<\/code> situ\xE9 au centre d'un <code>panneau d'ancrage<\/code>. Si des contenus relativement volumineux sont ins\xE9r\xE9s au milieu de ce panneau \xE0 d\xE9filement et si sa taille est d\xE9finie, il prend la forme d'une zone dot\xE9e d'une fonction de d\xE9filement \xE0 l'int\xE9rieur de la page, sans l'utilisation d'un IFRAME.<br><br>Voici un texte encore plus obscur qui va surtout servir \xE0 faire d\xE9filer cet \xE9l\xE9ment jusqu'en bas de sa zone visible. Sinon, il vous faudra r\xE9duire ce panneau \xE0 une taille minuscule pour pouvoir afficher ces formidables barres de d\xE9filement!"),c=new r1b(b),JYb(c.cb,IFc,iMc),JYb(c.cb,HFc,jMc),f6b(a,c,Z5b),g6b(a,'cwDockPanel'),a))};Pfb(1051,1007,RCc,n6b);_.Db=function o6b(a){g6b(this,a)};_.Wb=function p6b(a){var b;b=Y$b(this,a);if(b){a==this.a&&(this.a=null);h6b(this)}return b};var Z5b,$5b,_5b,a6b,b6b,c6b,d6b;Pfb(1052,1,{},r6b);Pfb(1053,1,{96:1},t6b);Pfb(1054,1,{97:1},v6b);_.a=0;var Q8=Nrc(lKc,'DockPanel',1051),P8=Nrc(lKc,'DockPanel$TmpRow',1054),xeb=Mrc(sKc,'DockPanel$TmpRow;',1385,P8),N8=Nrc(lKc,'DockPanel$DockLayoutConstant',1052),O8=Nrc(lKc,'DockPanel$LayoutData',1053);oEc(In)(11);