function Wyb(a){this.a=a}
function Zyb(a){this.a=a}
function azb(a){this.a=a}
function SG(a){AG();return new RG(yG.Td(),a,false)}
function Qyb(a,b){if(b==null){Ri(a.c,nOc)}else{p4b(a.c,b);Ki(a.c,nOc)}}
function Wjb(a){var b,c;b=wV(a.a.je(iOc),148);if(b==null){c=mV(Ieb,OCc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.a.le(iOc,c);return c}else{return b}}
function Ryb(b){var c,d,e;d=(zYb(),Hr(b.f.cb,mLc));if(Rsc(d,hFc)){p4b(b.c,oOc)}else{try{e=Zrc(d);c=FG(b.a,e);p4b(b.c,c);Qyb(b,null)}catch(a){a=Seb(a);if(yV(a,144)){Qyb(b,pOc)}else throw Reb(a)}}}
function Pyb(a){var b,c,d,e,f;b=new F7b(4,2);zYb();Rr(b.o,wJc,5);a.e=new bac;Zi(a.e,jOc);f=Wjb(a.b);for(d=0,e=f.length;d<e;++d){c=f[d];Y9b(a.e,c)}qj(a.e,new Wyb(a),(ky(),ky(),jy));V6b(b,0,0,kOc);Y6b(b,0,1,a.e);a.d=new Occ;Zi(a.d,jOc);qj(a.d,new Zyb(a),(Zy(),Zy(),Yy));Y6b(b,1,1,a.d);a.f=new Occ;Zi(a.f,jOc);Ecc(a.f,'31415926535.897932');qj(a.f,new azb(a),Yy);V6b(b,2,0,lOc);Y6b(b,2,1,a.f);a.c=new r4b;Zi(a.c,jOc);V6b(b,3,0,mOc);Y6b(b,3,1,a.c);Syb(a);return b}
function Syb(b){var c;switch(b.e.cb.selectedIndex){case 0:b.a=(AG(),!vG&&(vG=new RG(yG.Ud(),sD((SC(),RC)),false)),AG(),vG);Ecc(b.d,b.a.t);B_b(b.d,false);break;case 1:b.a=(AG(),!uG&&(uG=SG(sD((SC(),RC)))),AG(),uG);Ecc(b.d,b.a.t);B_b(b.d,false);break;case 2:b.a=(AG(),!xG&&(xG=new RG(yG.ee(),sD((SC(),RC)),false)),AG(),xG);Ecc(b.d,b.a.t);B_b(b.d,false);break;case 3:b.a=(AG(),!wG&&(wG=new RG(yG.de(),sD((SC(),RC)),false)),AG(),wG);Ecc(b.d,b.a.t);B_b(b.d,false);break;case 4:B_b(b.d,true);c=(zYb(),Hr(b.d.cb,mLc));try{b.a=(AG(),new RG(c,sD((SC(),RC)),true))}catch(a){a=Seb(a);if(yV(a,140)){Qyb(b,qOc);return}else throw Reb(a)}}Ryb(b)}
var fOc='#,##0.00\xA0\xA4',gOc='#,##0\xA0%',hOc='#E0',iOc='cwNumberFormatPatterns';var uG,wG,xG;Pfb(357,1,{});_.Td=function dH(){return fOc};_.de=function pH(){return gOc};_.ee=function qH(){return hOc};Pfb(358,1,{});_.Td=function uH(){return fOc};_.de=function GH(){return gOc};_.ee=function HH(){return hOc};Pfb(359,1,{});_.Td=function LH(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.de=function XH(){return gOc};_.ee=function YH(){return hOc};Pfb(360,1,{});_.Td=function aI(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.de=function mI(){return gOc};_.ee=function nI(){return hOc};Pfb(361,1,{});_.Td=function rI(){return fOc};_.de=function DI(){return gOc};_.ee=function EI(){return hOc};Pfb(362,1,{});_.Td=function II(){return fOc};_.de=function UI(){return gOc};_.ee=function VI(){return hOc};Pfb(673,1,zDc,Wyb);_.Cc=function Xyb(a){Syb(this.a)};Pfb(674,1,jDc,Zyb);_.Fc=function $yb(a){Syb(this.a)};Pfb(675,1,jDc,azb);_.Fc=function bzb(a){Ryb(this.a)};Pfb(676,1,BDc);_.lc=function fzb(){yib(this.b,Pyb(this.a))};var y3=Nrc(uKc,'CwNumberFormat$1',673),z3=Nrc(uKc,'CwNumberFormat$2',674),A3=Nrc(uKc,'CwNumberFormat$3',675);oEc(In)(25);