function SJ(a){this.a=a}
function YJ(a){this.b=a}
function BAb(){this.a=new KCc}
function bK(){throw new uwc}
function uJ(b,a){return b.b[BJc+a]}
function cK(a,b){this.a=a;this.b=b}
function Iyb(a,b){this.a=a;this.b=b}
function tJ(a,b){return HV(b,1)?uJ(a,FV(b,1)):null}
function vJ(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[BJc+a[c]]=b[c]}}
function XJ(a){var b;if(a.a>=a.b.a.a.length){throw new NDc}b=a.b.a.a[a.a++];return new cK(b,uJ(a.b.a,b))}
function AAb(a){var b;b=FV(a.a.ke(kkd),159);if(!b){b=new vJ(vV($eb,lFc,1,[Zed,Ved,bfd,Xed,dfd,_ed,lkd,mkd]),vV($eb,lFc,1,[nkd,okd,pkd,qkd,rkd,skd,tkd,ukd]));a.a.me(kkd,b)}return b}
function Eyb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new BAb;n=new g9b;i=FV(n.j,99);m$b();Sr(n.o,hWc,5);q=Xib(V3);o=new L1b(q);rj(o,new Iyb(a,q),(Dy(),Dy(),Cy));p=new Zac;Sr(p.e,hWc,3);Wac(p,new z6b(ekd));Wac(p,o);a9b(n,0,0,p);Sr(p9b(i,0),C9c,2);g=new Vec;Tr(g.cb,F9c,fkd);MC(g.a);x$b(g.cb,PIc,Uid);Z8b(n,1,0,gkd);a9b(n,1,1,g);k=new Vec;Tr(k.cb,F9c,hkd);MC(k.a);x$b(k.cb,PIc,Uid);Z8b(n,2,0,ikd);a9b(n,2,1,k);b=new fcc;c=AAb(f);for(e=c.je().$b();e.ve();){d=FV(e.we(),160);j=FV(d.ye(),1);r=FV(d.Mc(),1);bcc(b,r,j,-1)}Z8b(n,3,0,jkd);a9b(n,3,1,b);return n}
var jkd='<b>Couleur Pr\xE9f\xE9r\xE9e:<\/b>',ikd='<b>Nom:<\/b>',gkd='<b>Pr\xE9nom:<\/b>',fkd='Amelie',ekd="Cet exemple interagit avec l'\xE9chatillon de l'interface:",ykd='ConstantMap',Akd='ConstantMap$1',Bkd='ConstantMap$1$1',zkd='ConstantMap$EntryImpl',hkd='Crutcher',wkd='CwConstantsExample$1',vkd='ExampleConstants',xkd='ExampleConstants_fr',kkd='colorMap';fgb(364,365,LFc,vJ);_.he=function wJ(a){return (HV(a,1)?uJ(this,FV(a,1)):null)!=null};_.je=function xJ(){return new SJ(this)};_.ke=function yJ(a){return HV(a,1)?uJ(this,FV(a,1)):null};_.oe=function zJ(){return this.a.length};fgb(366,367,NFc,SJ);_.re=function TJ(a){var b,c;if(!HV(a,160)){return false}b=FV(a,160);c=tJ(this.a,b.ye());if(c!=null&&ovc(c,b.Mc())){return true}return false};_.$b=function UJ(){return new YJ(this)};_.oe=function VJ(){return this.a.a.length};fgb(369,1,{},YJ);_.ve=function ZJ(){return this.a<this.b.a.a.length};_.we=function $J(){return XJ(this)};_.xe=function _J(){throw new uwc};_.a=0;fgb(370,1,OFc,cK);_.eQ=function dK(a){var b;if(HV(a,160)){b=FV(a,160);if(ovc(this.a,b.ye())&&ovc(this.b,b.Mc())){return true}}return false};_.ye=function eK(){return this.a};_.Mc=function fK(){return this.b};_.hC=function gK(){var a,b;a=0;b=0;this.a!=null&&(a=Uvc(this.a));this.b!=null&&(b=Uvc(this.b));return a^b};_.ze=function hK(a){return bK(FV(a,1))};_.tS=function iK(){return this.a+HLc+this.b};fgb(659,1,YFc,Iyb);_.Ec=function Jyb(a){Qib(this.a,this.b+vjd)};fgb(660,1,_Fc);_.mc=function Nyb(){ojb(this.b,Eyb(this.a))};fgb(685,1,{},BAb);var V3=muc(z$c,vkd),s3=kuc(z$c,wkd,659),U3=kuc(z$c,xkd,685),j_=kuc(n2c,ykd,364),i_=kuc(n2c,zkd,370),h_=kuc(n2c,Akd,366),g_=kuc(n2c,Bkd,369);NGc(Jn)(30);