function AH(){}
function J_b(a,b){EC(a.a,b)}
function Jsb(a,b){this.b=a;this.a=b}
function Msb(a,b){this.b=a;this.a=b}
function ZH(a){return O3(KH,a)}
function zH(){zH=Opc;yH=new AH}
function Bsb(a,b){vTb(b,'\u5DF2\u9009\u62E9: '+a.cg()+Utc+a.dg())}
function W_b(){R_b();V_b.call(this,Zr($doc,'password'),'gwt-PasswordTextBox')}
function H8b(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;return c.text.length}catch(a){return 0}}
function G8b(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;return -c.move(pzc,-65535)}catch(a){return 0}}
function zsb(a,b){var c,d;c=new _Xb;FLb();Rr(c.e,xwc,4);YXb(c,a);if(b){d=new zTb('\u5DF2\u9009\u62E9: 0, 0');qj(a,new Jsb(a,d),(Zy(),Zy(),Yy));qj(a,new Msb(a,d),(uy(),uy(),ty));YXb(c,d)}return c}
function J8b(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return 0;var d=c.text.length;var e=0;var f=c.duplicate();f.moveEnd(pzc,-1);var g=f.text.length;while(g==d&&f.parentElement()==b&&c.compareEndPoints('StartToEnd',f)<=0){e+=2;f.moveEnd(pzc,-1);g=f.text.length}return d+e}catch(a){return 0}}
function I8b(b){try{var c=b.document.selection.createRange();if(c.parentElement()!==b)return -1;var d=c.duplicate();d.moveToElementText(b);d.setEndPoint('EndToStart',c);var e=d.text.length;var f=0;var g=d.duplicate();g.moveEnd(pzc,-1);var i=g.text.length;while(i==e&&g.parentElement()==b){f+=2;g.moveEnd(pzc,-1);i=g.text.length}return e+f}catch(a){return 0}}
function Asb(){var a,b,c,d,e,f;f=new r7b;FLb();Rr(f.e,xwc,5);d=new U_b;U6b(d.cb,nsc,'cwBasicText-textbox');J_b(d,(zH(),zH(),yH));b=new U_b;U6b(b.cb,nsc,'cwBasicText-textbox-disabled');K_b(b,ozc);Qr(b.cb,gyc,true);o7b(f,new ETb('<b>\u5E38\u89C4\u6587\u672C\u6846:<\/b>'));o7b(f,zsb(d,true));o7b(f,zsb(b,false));c=new W_b;U6b(c.cb,nsc,'cwBasicText-password');a=new W_b;U6b(a.cb,nsc,'cwBasicText-password-disabled');K_b(a,ozc);Qr(a.cb,gyc,true);o7b(f,new ETb('<br><br><b>\u5BC6\u7801\u6587\u672C\u6846:<\/b>'));o7b(f,zsb(c,true));o7b(f,zsb(a,false));e=new f5b;U6b(e.cb,nsc,'cwBasicText-textarea');e.cb.rows=5;o7b(f,new ETb('<br><br><b>\u6587\u672C\u533A\u57DF:<\/b>'));o7b(f,zsb(e,true));return f}
var pzc='character',ozc='\u53EA\u8BFB';W2(367,368,{},AH);_.xd=function BH(a){return ZH((TH(),a))?(cF(),bF):(cF(),aF)};var yH;W2(752,1,Hqc);_.lc=function Hsb(){F5(this.a,Asb())};W2(753,1,pqc,Jsb);_.Fc=function Ksb(a){Bsb(this.b,this.a)};W2(754,1,Eqc,Msb);_.Dc=function Nsb(a){Bsb(this.b,this.a)};W2(1097,979,Wpc);_.cg=function M_b(){return G8b(this.cb)};_.dg=function N_b(){return H8b(this.cb)};W2(1094,1095,Wpc,W_b);W2(1150,1096,Wpc);_.cg=function g5b(){return I8b(this.cb)};_.dg=function h5b(){return J8b(this.cb)};var dU=Tec(sxc,'CwBasicText$2',753),eU=Tec(sxc,'CwBasicText$3',754),aZ=Tec(mxc,'PasswordTextBox',1094),zO=Tec(Oxc,'AnyRtlDirectionEstimator',367);urc(In)(18);