function YAc(){}
function aBc(){}
function RAc(a,b){a.c=b}
function SAc(a){if(a==HAc){return true}SH();return a==KAc}
function TAc(a){if(a==GAc){return true}SH();return a==FAc}
function $Ac(a){this.c=(RCc(),MCc).b;this.e=(YCc(),XCc).b;this.b=a}
function PAc(a,b){var c;c=Wmb(a.bb,95);c.c=b.b;!!c.d&&Ouc(c.d,b)}
function QAc(a,b){var c;c=Wmb(a.bb,95);c.e=b.b;!!c.d&&arc(c.d,Rcd,b.b)}
function LAc(){LAc=v5c;EAc=new YAc;HAc=new YAc;GAc=new YAc;FAc=new YAc;IAc=new YAc;JAc=new YAc;KAc=new YAc}
function UAc(){LAc();Quc.call(this);this.c=(RCc(),MCc);this.d=(YCc(),XCc);Sqc();xs(this.f,Scd,0);xs(this.f,Tcd,0)}
function MAc(a,b,c){var d;if(c==EAc){if(b==a.b){return}else if(a.b){throw new PWc('Only one CENTER widget may be added')}}Kj(b);UOc(a.k,b);c==EAc&&(a.b=b);d=new $Ac(c);b.bb=d;PAc(b,a.c);QAc(b,a.d);OAc(a);Mj(b,a)}
function NAc(a,b){var c,d,e,f,g,i,j;rOc(a.db,Y7c,b);i=new $2c;j=new dPc(a.k);while(j.c<j.d.d){c=bPc(j);g=Wmb(c.bb,95).b;e=Wmb(i.re(g),141);d=!e?1:e.b;f=g==IAc?'north'+d:g==JAc?'south'+d:g==KAc?'west'+d:g==FAc?'east'+d:g==HAc?'linestart'+d:g==GAc?'lineend'+d:Hcd;rOc((Sqc(),Ss(c.db)),b,f);i.te(g,dXc(d+1))}}
function OAc(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t;b=a.e;while((Sqc(),Dsc(b))>0){ds(b,Csc(b,0))}q=1;e=1;for(i=new dPc(a.k);i.c<i.d.d;){d=bPc(i);f=Wmb(d.bb,95).b;f==IAc||f==JAc?++q:(f==FAc||f==KAc||f==HAc||f==GAc)&&++e}r=Lmb(mJb,B5c,96,q,0);for(g=0;g<q;++g){r[g]=new aBc;r[g].c=$doc.createElement(Pcd);Tqc(b,r[g].c)}k=0;n=e-1;o=0;s=q-1;c=null;for(i=new dPc(a.k);i.c<i.d.d;){d=bPc(i);j=Wmb(d.bb,95);t=$doc.createElement(Qcd);j.d=t;ys(j.d,zcd,j.c);arc(j.d,Rcd,j.e);ys(j.d,x8c,Y7c);ys(j.d,w8c,Y7c);if(j.b==IAc){Vqc(r[o].c,t,r[o].b);Tqc(t,d.db);xs(t,Ked,n-k+1);++o}else if(j.b==JAc){Vqc(r[s].c,t,r[s].b);Tqc(t,d.db);xs(t,Ked,n-k+1);--s}else if(j.b==EAc){c=t}else if(SAc(j.b)){p=r[o];Vqc(p.c,t,p.b++);Tqc(t,d.db);xs(t,Dfd,s-o+1);++k}else if(TAc(j.b)){p=r[o];Vqc(p.c,t,p.b);Tqc(t,d.db);xs(t,Dfd,s-o+1);--n}}if(a.b){p=r[o];Vqc(p.c,c,p.b);Tqc(c,a.b.db)}}
EKb(811,1,p6c);_.qc=function m6b(){var a,b,c;iNb(this.b,(a=new UAc,vj(a.db,'cw-DockPanel'),Sqc(),xs(a.f,Scd,4),RAc(a,(RCc(),LCc)),MAc(a,new dzc('This is the first north component'),(LAc(),IAc)),MAc(a,new dzc('This is the first south component'),JAc),MAc(a,new dzc('This is the east component'),FAc),MAc(a,new dzc('This is the west component'),KAc),MAc(a,new dzc('This is the second north component'),IAc),MAc(a,new dzc('This is the second south component'),JAc),b=new dzc("This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!"),c=new Yvc(b),arc(c.db,x8c,Bfd),arc(c.db,w8c,Cfd),MAc(a,c,EAc),NAc(a,'cwDockPanel'),a))};EKb(1114,1070,F5c,UAc);_.Ib=function VAc(a){NAc(this,a)};_._b=function WAc(a){var b;b=Atc(this,a);if(b){a==this.b&&(this.b=null);OAc(this)}return b};var EAc,FAc,GAc,HAc,IAc,JAc,KAc;EKb(1115,1,{},YAc);EKb(1116,1,{95:1},$Ac);EKb(1117,1,{96:1},aBc);_.b=0;var DDb=zWc(Gdd,'DockPanel',1114),CDb=zWc(Gdd,'DockPanel$TmpRow',1117),mJb=yWc(Ndd,'DockPanel$TmpRow;',1448,CDb),ADb=zWc(Gdd,'DockPanel$DockLayoutConstant',1115),BDb=zWc(Gdd,'DockPanel$LayoutData',1116);c7c(Vn)(11);