function Nyb(a){this.a=a}
function Qyb(a){this.a=a}
function Tyb(a){this.a=a}
function IG(a){qG();return new HG(oG.Td(),a,false)}
function Hyb(a,b){if(b==null){Ri(a.c,_Nc)}else{e4b(a.c,b);Ki(a.c,_Nc)}}
function Njb(a){var b,c;b=mV(a.a.je(WNc),148);if(b==null){c=cV(zeb,BCc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.a.le(WNc,c);return c}else{return b}}
function Iyb(b){var c,d,e;d=(cYb(),Ir(b.f.cb,_Kc));if(Esc(d,WEc)){e4b(b.c,aOc)}else{try{e=Mrc(d);c=vG(b.a,e);e4b(b.c,c);Hyb(b,null)}catch(a){a=Jeb(a);if(oV(a,144)){Hyb(b,bOc)}else throw Ieb(a)}}}
function Gyb(a){var b,c,d,e,f;b=new u7b(4,2);cYb();Sr(b.o,kJc,5);a.e=new S9b;Zi(a.e,XNc);f=Njb(a.b);for(d=0,e=f.length;d<e;++d){c=f[d];N9b(a.e,c)}rj(a.e,new Nyb(a),(ay(),ay(),_x));K6b(b,0,0,YNc);N6b(b,0,1,a.e);a.d=new Dcc;Zi(a.d,XNc);rj(a.d,new Qyb(a),(Py(),Py(),Oy));N6b(b,1,1,a.d);a.f=new Dcc;Zi(a.f,XNc);tcc(a.f,'31415926535.897932');rj(a.f,new Tyb(a),Oy);K6b(b,2,0,ZNc);N6b(b,2,1,a.f);a.c=new g4b;Zi(a.c,XNc);K6b(b,3,0,$Nc);N6b(b,3,1,a.c);Jyb(a);return b}
function Jyb(b){var c;switch(b.e.cb.selectedIndex){case 0:b.a=(qG(),!lG&&(lG=new HG(oG.Ud(),iD((IC(),HC)),false)),qG(),lG);tcc(b.d,b.a.t);q_b(b.d,false);break;case 1:b.a=(qG(),!kG&&(kG=IG(iD((IC(),HC)))),qG(),kG);tcc(b.d,b.a.t);q_b(b.d,false);break;case 2:b.a=(qG(),!nG&&(nG=new HG(oG.ee(),iD((IC(),HC)),false)),qG(),nG);tcc(b.d,b.a.t);q_b(b.d,false);break;case 3:b.a=(qG(),!mG&&(mG=new HG(oG.de(),iD((IC(),HC)),false)),qG(),mG);tcc(b.d,b.a.t);q_b(b.d,false);break;case 4:q_b(b.d,true);c=(cYb(),Ir(b.d.cb,_Kc));try{b.a=(qG(),new HG(c,iD((IC(),HC)),true))}catch(a){a=Jeb(a);if(oV(a,140)){Hyb(b,cOc);return}else throw Ieb(a)}}Iyb(b)}
var TNc='#,##0.00\xA0\xA4',UNc='#,##0\xA0%',VNc='#E0',WNc='cwNumberFormatPatterns';var kG,mG,nG;Gfb(358,1,{});_.Td=function VG(){return TNc};_.de=function fH(){return UNc};_.ee=function gH(){return VNc};Gfb(359,1,{});_.Td=function kH(){return TNc};_.de=function wH(){return UNc};_.ee=function xH(){return VNc};Gfb(360,1,{});_.Td=function BH(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.de=function NH(){return UNc};_.ee=function OH(){return VNc};Gfb(361,1,{});_.Td=function SH(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.de=function cI(){return UNc};_.ee=function dI(){return VNc};Gfb(362,1,{});_.Td=function hI(){return TNc};_.de=function tI(){return UNc};_.ee=function uI(){return VNc};Gfb(363,1,{});_.Td=function yI(){return TNc};_.de=function KI(){return UNc};_.ee=function LI(){return VNc};Gfb(674,1,mDc,Nyb);_.Cc=function Oyb(a){Jyb(this.a)};Gfb(675,1,YCc,Qyb);_.Fc=function Ryb(a){Jyb(this.a)};Gfb(676,1,YCc,Tyb);_.Fc=function Uyb(a){Iyb(this.a)};Gfb(677,1,oDc);_.lc=function Yyb(){pib(this.b,Gyb(this.a))};var o3=Arc(hKc,'CwNumberFormat$1',674),p3=Arc(hKc,'CwNumberFormat$2',675),q3=Arc(hKc,'CwNumberFormat$3',676);bEc(Jn)(25);