function uzb(a){this.b=a}
function xzb(a){this.b=a}
function Azb(a){this.b=a}
function mH(a){WG();return new lH(UG._d(),a,false)}
function ozb(a,b){if(b==null){bj(a.d,ZOc)}else{K4b(a.d,b);Wi(a.d,ZOc)}}
function ukb(a){var b,c;b=SV(a.b.re(UOc),147);if(b==null){c=IV(lfb,nDc,1,['D\xE9cimales','devise','scientifique','pourcentage','personnalis\xE9']);a.b.te(UOc,c);return c}else{return b}}
function pzb(b){var c,d,e;d=(GYb(),ns(b.g.db,YLc));if(otc(d,JFc)){K4b(b.d,$Oc)}else{try{e=wsc(d);c=_G(b.b,e);K4b(b.d,c);ozb(b,null)}catch(a){a=vfb(a);if(UV(a,143)){ozb(b,_Oc)}else throw ufb(a)}}}
function nzb(a){var b,c,d,e,f;b=new a8b(4,2);GYb();xs(b.p,hKc,5);a.f=new yac;jj(a.f,VOc);f=ukb(a.c);for(d=0,e=f.length;d<e;++d){c=f[d];tac(a.f,c)}Dj(a.f,new uzb(a),(Hy(),Hy(),Gy));o7b(b,0,0,WOc);r7b(b,0,1,a.f);a.e=new kdc;jj(a.e,VOc);Dj(a.e,new xzb(a),(uz(),uz(),tz));r7b(b,1,1,a.e);a.g=new kdc;jj(a.g,VOc);adc(a.g,'31415926535.897932');Dj(a.g,new Azb(a),tz);o7b(b,2,0,XOc);r7b(b,2,1,a.g);a.d=new M4b;jj(a.d,VOc);o7b(b,3,0,YOc);r7b(b,3,1,a.d);qzb(a);return b}
function qzb(b){var c;switch(b.f.db.selectedIndex){case 0:b.b=(WG(),!RG&&(RG=new lH(UG.ae(),OD((mD(),lD)),false)),WG(),RG);adc(b.e,b.b.u);V_b(b.e,false);break;case 1:b.b=(WG(),!QG&&(QG=mH(OD((mD(),lD)))),WG(),QG);adc(b.e,b.b.u);V_b(b.e,false);break;case 2:b.b=(WG(),!TG&&(TG=new lH(UG.me(),OD((mD(),lD)),false)),WG(),TG);adc(b.e,b.b.u);V_b(b.e,false);break;case 3:b.b=(WG(),!SG&&(SG=new lH(UG.le(),OD((mD(),lD)),false)),WG(),SG);adc(b.e,b.b.u);V_b(b.e,false);break;case 4:V_b(b.e,true);c=(GYb(),ns(b.e.db,YLc));try{b.b=(WG(),new lH(c,OD((mD(),lD)),true))}catch(a){a=vfb(a);if(UV(a,139)){ozb(b,aPc);return}else throw ufb(a)}}pzb(b)}
var ROc='#,##0.00\xA0\xA4',SOc='#,##0\xA0%',TOc='#E0',UOc='cwNumberFormatPatterns';var QG,SG,TG;sgb(360,1,{});_._d=function zH(){return ROc};_.le=function LH(){return SOc};_.me=function MH(){return TOc};sgb(361,1,{});_._d=function QH(){return ROc};_.le=function aI(){return SOc};_.me=function bI(){return TOc};sgb(362,1,{});_._d=function fI(){return '#,##0.00\xA0\xA4;(#,##0.00\xA0\xA4)'};_.le=function rI(){return SOc};_.me=function sI(){return TOc};sgb(363,1,{});_._d=function wI(){return '\xA4\xA0#,##0.00;\xA4-#,##0.00'};_.le=function II(){return SOc};_.me=function JI(){return TOc};sgb(364,1,{});_._d=function NI(){return ROc};_.le=function ZI(){return SOc};_.me=function $I(){return TOc};sgb(365,1,{});_._d=function cJ(){return ROc};_.le=function oJ(){return SOc};_.me=function pJ(){return TOc};sgb(675,1,$Dc,uzb);_.Kc=function vzb(a){qzb(this.b)};sgb(676,1,KDc,xzb);_.Nc=function yzb(a){qzb(this.b)};sgb(677,1,KDc,Azb);_.Nc=function Bzb(a){pzb(this.b)};sgb(678,1,aEc);_.qc=function Fzb(){Yib(this.c,nzb(this.b))};var $3=ksc(eLc,'CwNumberFormat$1',675),_3=ksc(eLc,'CwNumberFormat$2',676),a4=ksc(eLc,'CwNumberFormat$3',677);PEc(Vn)(25);