function HCc(){}
function LCc(){}
function ACc(a,b){a.b=b}
function BCc(a){if(a==qCc){return true}FH();return a==tCc}
function CCc(a){if(a==pCc){return true}FH();return a==oCc}
function JCc(a){this.b=(yEc(),tEc).a;this.d=(FEc(),EEc).a;this.a=a}
function yCc(a,b){var c;c=Jmb(a.ab,97);c.b=b.a;!!c.c&&uwc(c.c,b)}
function zCc(a,b){var c;c=Jmb(a.ab,97);c.d=b.a;!!c.c&&Jsc(c.c,vod,b.a)}
function DCc(){uCc();wwc.call(this);this.b=(yEc(),tEc);this.c=(FEc(),EEc);ysc();Sr(this.e,wod,0);Sr(this.e,xod,0)}
function uCc(){uCc=u7c;nCc=new HCc;qCc=new HCc;pCc=new HCc;oCc=new HCc;rCc=new HCc;sCc=new HCc;tCc=new HCc}
function vCc(a,b,c){var d;if(c==nCc){if(b==a.a){return}else if(a.a){throw new PYc(HHd)}}yj(b);OQc(a.j,b);c==nCc&&(a.a=b);d=new JCc(c);b.ab=d;yCc(b,a.b);zCc(b,a.c);xCc(a);Aj(b,a)}
function wCc(a,b){var c,d,e,f,g,i,j;lQc(a.cb,X9c,b);i=new Z4c;j=new ZQc(a.j);while(j.b<j.c.c){c=XQc(j);g=Jmb(c.ab,97).a;e=Jmb(i.ke(g),143);d=!e?1:e.a;f=g==rCc?IHd+d:g==sCc?JHd+d:g==tCc?KHd+d:g==oCc?LHd+d:g==qCc?MHd+d:g==pCc?NHd+d:god;lQc((ysc(),ks(c.cb)),b,f);i.me(g,dZc(d+1))}}
function xCc(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t;b=a.d;while((ysc(),b.children.length)>0){yr(b,b.children[0])}q=1;e=1;for(i=new ZQc(a.j);i.b<i.c.c;){d=XQc(i);f=Jmb(d.ab,97).a;f==rCc||f==sCc?++q:(f==oCc||f==tCc||f==qCc||f==pCc)&&++e}r=ymb(_Ib,z7c,98,q,0);for(g=0;g<q;++g){r[g]=new LCc;r[g].b=qs($doc,tod);zsc(b,r[g].b)}k=0;n=e-1;o=0;s=q-1;c=null;for(i=new ZQc(a.j);i.b<i.c.c;){d=XQc(i);j=Jmb(d.ab,97);t=qs($doc,uod);j.c=t;Tr(j.c,Snd,j.b);Jsc(j.c,vod,j.d);Tr(j.c,cbd,X9c);Tr(j.c,bbd,X9c);if(j.a==rCc){Bsc(r[o].b,t,r[o].a);zsc(t,d.cb);Sr(t,RDd,n-k+1);++o}else if(j.a==sCc){Bsc(r[s].b,t,r[s].a);zsc(t,d.cb);Sr(t,RDd,n-k+1);--s}else if(j.a==nCc){c=t}else if(BCc(j.a)){p=r[o];Bsc(p.b,t,p.a++);zsc(t,d.cb);Sr(t,OHd,s-o+1);++k}else if(CCc(j.a)){p=r[o];Bsc(p.b,t,p.a);zsc(t,d.cb);Sr(t,OHd,s-o+1);--n}}if(a.a){p=r[o];Bsc(p.b,c,p.a);zsc(c,a.a.cb)}}
var PHd='DockPanel',SHd='DockPanel$DockLayoutConstant',THd='DockPanel$LayoutData',QHd='DockPanel$TmpRow',RHd='DockPanel$TmpRow;',HHd='Only one CENTER widget may be added',DHd="This is a <code>ScrollPanel<\/code> contained at the center of a <code>DockPanel<\/code>.  By putting some fairly large contents in the middle and setting its size explicitly, it becomes a scrollable area within the page, but without requiring the use of an IFRAME.<br><br>Here's quite a bit more meaningless text that will serve primarily to make this thing scroll off the bottom of its visible area.  Otherwise, you might have to make it really, really small in order to see the nifty scroll bars!",zHd='This is the east component',xHd='This is the first north component',yHd='This is the first south component',BHd='This is the second north component',CHd='This is the second south component',AHd='This is the west component',wHd='cw-DockPanel',GHd='cwDockPanel',LHd='east',NHd='lineend',MHd='linestart',IHd='north',JHd='south',KHd='west';rKb(813,1,o8c);_.mc=function Y6b(){var a,b,c;ANb(this.a,(a=new DCc,jj(a.cb,wHd),ysc(),Sr(a.e,wod,4),ACc(a,(yEc(),sEc)),vCc(a,new LAc(xHd),(uCc(),rCc)),vCc(a,new LAc(yHd),sCc),vCc(a,new LAc(zHd),oCc),vCc(a,new LAc(AHd),tCc),vCc(a,new LAc(BHd),rCc),vCc(a,new LAc(CHd),sCc),b=new LAc(DHd),c=new Exc(b),Jsc(c.cb,cbd,EHd),Jsc(c.cb,bbd,FHd),vCc(a,c,nCc),wCc(a,GHd),a))};rKb(1118,1074,D7c,DCc);_.Eb=function ECc(a){wCc(this,a)};_.Xb=function FCc(a){var b;b=jvc(this,a);if(b){a==this.a&&(this.a=null);xCc(this)}return b};var nCc,oCc,pCc,qCc,rCc,sCc,tCc;rKb(1119,1,{},HCc);rKb(1120,1,{97:1},JCc);rKb(1121,1,{98:1},LCc);_.a=0;var nDb=zYc(wrd,PHd,1118),mDb=zYc(wrd,QHd,1121),_Ib=yYc(Jsd,RHd,1457,mDb),kDb=zYc(wrd,SHd,1119),lDb=zYc(wrd,THd,1120);a9c(Jn)(11);