function zJ(a){this.a=a}
function FJ(a){this.b=a}
function ozb(){this.a=new cAc}
function KJ(){throw new Otc}
function bJ(b,a){return b.b[SFc+a]}
function LJ(a,b){this.a=a;this.b=b}
function vxb(a,b){this.a=a;this.b=b}
function aJ(a,b){return oV(b,1)?bJ(a,mV(b,1)):null}
function cJ(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[SFc+a[c]]=b[c]}}
function EJ(a){var b;if(a.a>=a.b.a.a.length){throw new fBc}b=a.b.a.a[a.a++];return new LJ(b,bJ(a.b.a,b))}
function nzb(a){var b;b=mV(a.a.je(oOc),158);if(!b){b=new cJ(cV(zeb,FCc,1,[kMc,hMc,nMc,jMc,oMc,mMc,pOc,qOc]),cV(zeb,FCc,1,[rOc,sOc,tOc,uOc,vOc,wOc,xOc,yOc]));a.a.le(oOc,b)}return b}
function rxb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new ozb;n=new U6b;i=mV(n.j,98);cYb();Sr(n.o,oJc,5);q=Yhb(z3);o=new z_b(q);rj(o,new vxb(a,q),(ky(),ky(),jy));p=new L8b;Sr(p.e,oJc,3);I8b(p,new n4b("Cet exemple interagit avec l'\xE9chatillon de l'interface:"));I8b(p,o);O6b(n,0,0,p);Sr(b7b(i,0),cLc,2);g=new Ecc;Tr(g.cb,dLc,'Amelie');tC(g.a);mYb(g.cb,zFc,_Nc);L6b(n,1,0,'<b>Pr\xE9nom:<\/b>');O6b(n,1,1,g);k=new Ecc;Tr(k.cb,dLc,'Crutcher');tC(k.a);mYb(k.cb,zFc,_Nc);L6b(n,2,0,'<b>Nom:<\/b>');O6b(n,2,1,k);b=new T9b;c=nzb(f);for(e=c.ie().Zb();e.ue();){d=mV(e.ve(),159);j=mV(d.xe(),1);r=mV(d.Lc(),1);P9b(b,r,j,-1)}L6b(n,3,0,'<b>Couleur Pr\xE9f\xE9r\xE9e:<\/b>');O6b(n,3,1,b);return n}
var oOc='colorMap';Gfb(364,365,dDc,cJ);_.ge=function dJ(a){return (oV(a,1)?bJ(this,mV(a,1)):null)!=null};_.ie=function eJ(){return new zJ(this)};_.je=function fJ(a){return oV(a,1)?bJ(this,mV(a,1)):null};_.ne=function gJ(){return this.a.length};Gfb(366,367,fDc,zJ);_.qe=function AJ(a){var b,c;if(!oV(a,159)){return false}b=mV(a,159);c=aJ(this.a,b.xe());if(c!=null&&Isc(c,b.Lc())){return true}return false};_.Zb=function BJ(){return new FJ(this)};_.ne=function CJ(){return this.a.a.length};Gfb(369,1,{},FJ);_.ue=function GJ(){return this.a<this.b.a.a.length};_.ve=function HJ(){return EJ(this)};_.we=function IJ(){throw new Otc};_.a=0;Gfb(370,1,gDc,LJ);_.eQ=function MJ(a){var b;if(oV(a,159)){b=mV(a,159);if(Isc(this.a,b.xe())&&Isc(this.b,b.Lc())){return true}}return false};_.xe=function NJ(){return this.a};_.Lc=function OJ(){return this.b};_.hC=function PJ(){var a,b;a=0;b=0;this.a!=null&&(a=mtc(this.a));this.b!=null&&(b=mtc(this.b));return a^b};_.ye=function QJ(a){return KJ(mV(a,1))};_.tS=function RJ(){return this.a+DGc+this.b};Gfb(656,1,pDc,vxb);_.Dc=function wxb(a){Rhb(this.a,this.b+kOc)};Gfb(657,1,sDc);_.lc=function Axb(){pib(this.b,rxb(this.a))};Gfb(682,1,{},ozb);var z3=Grc(lKc,'ExampleConstants'),Y2=Erc(lKc,'CwConstantsExample$1',656),y3=Erc(lKc,'ExampleConstants_fr',682),S$=Erc(AKc,'ConstantMap',364),R$=Erc(AKc,'ConstantMap$EntryImpl',370),Q$=Erc(AKc,'ConstantMap$1',366),P$=Erc(AKc,'ConstantMap$1$1',369);fEc(Jn)(30);