function vG(a){this.a=a}
function BG(a){this.b=a}
function vmb(){this.a=new hnc}
function GG(){throw new Tgc}
function ZF(b,a){return b.b[Xsc+a]}
function HG(a,b){this.a=a;this.b=b}
function Ckb(a,b){this.a=a;this.b=b}
function YF(a,b){return PI(b,1)?ZF(a,NI(b,1)):null}
function $F(a,b){var c;this.a=a;this.b={};for(c=0;c<a.length;++c){this.b[Xsc+a[c]]=b[c]}}
function AG(a){var b;if(a.a>=a.b.a.a.length){throw new koc}b=a.b.a.a[a.a++];return new HG(b,ZF(a.b.a,b))}
function umb(a){var b;b=NI(a.a.gd(hBc),158);if(!b){b=new $F(DI(G1,Kpc,1,[jzc,gzc,mzc,izc,nzc,lzc,iBc,jBc]),DI(G1,Kpc,1,[Qxc,kBc,lBc,mBc,Pxc,Rxc,nBc,oBc]));a.a.jd(hBc,b)}return b}
function ykb(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r;f=new vmb;n=new ZVb;i=NI(n.j,98);iLb();Sr(n.o,owc,5);q=d5(GS);o=new FOb(q);rj(o,new Ckb(a,q),(ky(),ky(),jy));p=new QXb;Sr(p.e,owc,3);NXb(p,new tTb(eBc));NXb(p,o);TVb(n,0,0,p);Sr(gWb(i,0),eyc,2);g=new J_b;Tr(g.cb,fyc,'Amelie');tC(g.a);sLb(g.cb,Esc,VAc);QVb(n,1,0,'<b>\u540D\u5B57\uFF1A<\/b>');TVb(n,1,1,g);k=new J_b;Tr(k.cb,fyc,'Crutcher');tC(k.a);sLb(k.cb,Esc,VAc);QVb(n,2,0,'<b>\u53BB\u5E74\u540D\u79F0\uFF1A<\/b>');TVb(n,2,1,k);b=new YYb;c=umb(f);for(e=c.fd().Zb();e.sd();){d=NI(e.td(),159);j=NI(d.vd(),1);r=NI(d.Lc(),1);UYb(b,r,j,-1)}QVb(n,3,0,'<b>\u6700\u559C\u7231\u7684\u989C\u8272\uFF1A<\/b>');TVb(n,3,1,b);return n}
var hBc='colorMap';N2(354,355,iqc,$F);_.dd=function _F(a){return (PI(a,1)?ZF(this,NI(a,1)):null)!=null};_.fd=function aG(){return new vG(this)};_.gd=function bG(a){return PI(a,1)?ZF(this,NI(a,1)):null};_.ld=function cG(){return this.a.length};N2(356,357,kqc,vG);_.od=function wG(a){var b,c;if(!PI(a,159)){return false}b=NI(a,159);c=YF(this.a,b.vd());if(c!=null&&Nfc(c,b.Lc())){return true}return false};_.Zb=function xG(){return new BG(this)};_.ld=function yG(){return this.a.a.length};N2(359,1,{},BG);_.sd=function CG(){return this.a<this.b.a.a.length};_.td=function DG(){return AG(this)};_.ud=function EG(){throw new Tgc};_.a=0;N2(360,1,lqc,HG);_.eQ=function IG(a){var b;if(PI(a,159)){b=NI(a,159);if(Nfc(this.a,b.vd())&&Nfc(this.b,b.Lc())){return true}}return false};_.vd=function JG(){return this.a};_.Lc=function KG(){return this.b};_.hC=function LG(){var a,b;a=0;b=0;this.a!=null&&(a=rgc(this.a));this.b!=null&&(b=rgc(this.b));return a^b};_.wd=function MG(a){return GG(NI(a,1))};_.tS=function NG(){return this.a+Itc+this.b};N2(635,1,uqc,Ckb);_.Dc=function Dkb(a){Y4(this.a,this.b+cBc)};N2(636,1,xqc);_.lc=function Hkb(){w5(this.b,ykb(this.a))};N2(661,1,{},vmb);var GS=Lec(lxc,'ExampleConstants'),dS=Jec(lxc,'CwConstantsExample$1',635),FS=Jec(lxc,'ExampleConstants_zh',661),iO=Jec(Axc,'ConstantMap',354),hO=Jec(Axc,'ConstantMap$EntryImpl',360),gO=Jec(Axc,'ConstantMap$1',356),fO=Jec(Axc,'ConstantMap$1$1',359);krc(Jn)(30);